export const otherCards = [
    {
        name: "Renoy Bright", 
        shortName: "Renoy",
        levelCard: 1,
        cate: "supra",
        attk: 43,
        def: 13,
        esse: 100,
        defeated: false, 
    },
    {
        name: "Chairman Sam",
        shortName: "Chairman", 
        levelCard: 1,
        cate: "fere",
        attk: 25,
        def: 19,
        esse: 100,
        defeated: false, 
    },
    {
        name: "Guard 1", 
        shortName: "Guard 1",
        levelCard: 1,
        cate: "bonum",
        attk: 14,
        def: 25,
        esse: 100, 
        defeated: false,
    },
    {
        name: "Guard 2",
        shortName: "Guard 2",
        levelCard: 1,
        cate: "bonum",
        attk: 14,
        def: 25,
        esse: 100, 
        defeated: false, 
    },

    {
        name: "Tales Venoy",
        shortName: "Tales",
        levelCard: 2,
        cate: "supra",
        attk: 0,
        def: 0,
        esse: 100,
        defeated: false, 
    }
]